repository:
  name: cv
  description: Torben Haack's Curriculum Vitae rendered with RenderCV.
  topics:
    - resume
    - cv
    - rendercv
    - python
  has_issues: false
  has_projects: false
  has_wiki: false
  has_downloads: true
  default_branch: main
  allow_squash_merge: true
  allow_merge_commit: false
  allow_rebase_merge: true
  delete_branch_on_merge: true
